### ISSUE TITLE
API Fuzzer Tracking - TODO

### ISSUE THREAD

**Issue by lalithr95** [lalithr95/API-fuzzer#1]
- [x] Information Leak which includes server information, version disclosures

- [x] Header info disclosure which detects Clickjacking, lack of HSTS, X-XSS protection etc.

- [x] XSS module which should detect all kinds of xss, which need to be done with regex match.

- [x] SQL injection Mostly error based which will be based on regex match of responses.

- [x] XXE check

- [x] Open Redirect vulnerability check

- [x] Privilege Escalation or IDOR specifically - Little complicated a generic approach need to be used.
- [x] API rate limit check

/cc: @abhijeth @srini0x00

**Comment by lalithr95** [comment]
Removing comments as gem is public
